# -*- coding: utf-8 -*-
"""DAVIS.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aeMOcQvd43jvCJuEyCbPjPnz7gyxChjZ
"""

try:
    from google.colab import drive
    drive.mount("/content/drive")
    DRIVE_AVAILABLE = True
    print("✅ Google Drive mounted at /content/drive")
except Exception:
    DRIVE_AVAILABLE = False
    print("⚠️ Google Drive not available — saving locally only")

import os, sys, math, hashlib, random, warnings, subprocess, json, shutil
from copy import deepcopy
from collections import Counter

warnings.filterwarnings("ignore")

def pip_install(pkgs):
    subprocess.check_call([sys.executable, "-m", "pip", "-q", "install"] + pkgs)

pip_install([
    "fair-esm",
    "transformers",
    "accelerate",
    "pandas",
    "numpy",
    "scikit-learn",
    "tqdm"
])

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset, DataLoader
from torch.optim.swa_utils import AveragedModel, SWALR, update_bn
from tqdm import tqdm

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    average_precision_score,
    matthews_corrcoef,
    confusion_matrix,
    precision_recall_curve,
)

from sklearn.linear_model import LogisticRegression
from transformers import AutoTokenizer, AutoModel


LOCAL_SAVE_DIR = "./davis_results_v4"
os.makedirs(LOCAL_SAVE_DIR, exist_ok=True)

DRIVE_SAVE_DIR = "/content/drive/MyDrive/DTI_Project_Checkpoints/DAVIS"

if DRIVE_AVAILABLE:
    os.makedirs(DRIVE_SAVE_DIR, exist_ok=True)
    print(f"📂 Drive save dir : {DRIVE_SAVE_DIR}")

SAVE_DIR = LOCAL_SAVE_DIR
print(f"📂 Local save dir : {SAVE_DIR}")

def mirror_to_drive(src_path: str):
    if not DRIVE_AVAILABLE:
        return
    dst_path = src_path.replace(LOCAL_SAVE_DIR, DRIVE_SAVE_DIR, 1)
    os.makedirs(os.path.dirname(dst_path), exist_ok=True)
    shutil.copy2(src_path, dst_path)

def drive_path(local_path: str) -> str:
    return local_path.replace(LOCAL_SAVE_DIR, DRIVE_SAVE_DIR, 1)




SEEDS = [42, 123, 456, 789, 1337]
all_results = []

def seed_everything(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)



if not os.path.exists("MolTrans"):
    subprocess.check_call([
        "bash",
        "-lc",
        "git clone https://github.com/kexinhuang12345/MolTrans.git"
    ])

DAVIS_BASE = os.path.join("MolTrans", "dataset", "DAVIS")
assert os.path.exists(DAVIS_BASE), f"DAVIS dataset not found at {DAVIS_BASE}"

print("DAVIS files:", os.listdir(DAVIS_BASE))




ESM_CACHE_DIR = os.path.join(SAVE_DIR, "esm_cache_davis")
DRUGTOK_CACHE_DIR = os.path.join(SAVE_DIR, "drugtok_cache_davis")

for d in [ESM_CACHE_DIR, DRUGTOK_CACHE_DIR]:
    os.makedirs(d, exist_ok=True)




import esm

esm_model, esm_alphabet = esm.pretrained.esm2_t12_35M_UR50D()
esm_model = esm_model.to(device).eval()
esm_batch_converter = esm_alphabet.get_batch_converter()
ESM_DIM = esm_model.embed_dim

print("ESM embedding dim:", ESM_DIM)

def md5(s: str) -> str:
    return hashlib.md5(s.encode("utf-8")).hexdigest()

@torch.no_grad()
def esm2_embed_sequence(seq: str, max_len: int = 1200, k: int = 3, use_cache: bool = True):
    seq_clean = (seq or "").replace(" ", "").upper()

    if len(seq_clean) == 0:
        return (
            torch.zeros((max_len, ESM_DIM), dtype=torch.float32),
            torch.zeros((max_len, max_len), dtype=torch.bool),
            torch.zeros((max_len,), dtype=torch.float32),
        )

    key = md5(f"{seq_clean}|L{max_len}|K{k}|esm2_t12_35M")
    fpath = os.path.join(ESM_CACHE_DIR, f"{key}.pt")

    if use_cache and os.path.exists(fpath):
        pack = torch.load(fpath, map_location="cpu")
        return pack["node_feats"], pack["adj"], pack["mask"]

    data = [("protein", seq_clean)]
    _, _, toks = esm_batch_converter(data)

    out = esm_model(toks.to(device), repr_layers=[esm_model.num_layers])
    rep = out["representations"][esm_model.num_layers][0, 1:-1, :].detach().cpu()

    L_use = min(rep.shape[0], max_len)

    node_feats = torch.zeros((max_len, ESM_DIM), dtype=torch.float32)
    node_feats[:L_use] = rep[:L_use]

    mask = torch.zeros((max_len,), dtype=torch.float32)
    mask[:L_use] = 1.0

    adj = torch.zeros((max_len, max_len), dtype=torch.bool)

    for i in range(L_use):
        left = max(0, i - k)
        right = min(L_use, i + k + 1)
        adj[i, left:right] = True
        adj[i, i] = False

    if use_cache:
        torch.save(
            {"node_feats": node_feats, "adj": adj, "mask": mask},
            fpath
        )

    return node_feats, adj, mask




drug_tok = AutoTokenizer.from_pretrained("seyonec/ChemBERTa-zinc-base-v1")

def clean_smiles(smiles: str) -> str:
    return str(smiles or "").strip().replace(" ", "")

def tokenize_drug_smiles(smiles: str, max_len: int = 128, use_cache: bool = True):
    s = clean_smiles(smiles)

    if not s:
        return (
            torch.zeros((max_len,), dtype=torch.long),
            torch.zeros((max_len,), dtype=torch.long),
        )

    key = md5(f"{s}|L{max_len}|{getattr(drug_tok, 'name_or_path', 'tok')}")
    fpath = os.path.join(DRUGTOK_CACHE_DIR, f"{key}.pt")

    if use_cache and os.path.exists(fpath):
        pack = torch.load(fpath, map_location="cpu")
        return pack["input_ids"], pack["attention_mask"]

    toks = drug_tok(
        s,
        max_length=max_len,
        padding="max_length",
        truncation=True,
        return_tensors="pt"
    )

    input_ids = toks["input_ids"].squeeze(0).cpu()
    attn_mask = toks["attention_mask"].squeeze(0).cpu()

    if use_cache:
        torch.save(
            {"input_ids": input_ids, "attention_mask": attn_mask},
            fpath
        )

    return input_ids, attn_mask




def _read_csv(path):
    df = pd.read_csv(path)
    df.columns = df.columns.str.strip()
    return df

def standardize_df(df: pd.DataFrame) -> pd.DataFrame:
    drug_col = next(
        (c for c in [
            "SMILES", "smiles", "Drug", "drug",
            "drug_smiles", "compound_iso_smiles"
        ] if c in df.columns),
        None
    )

    prot_col = next(
        (c for c in [
            "Target Sequence", "target_seq", "targetseq",
            "Protein", "protein", "sequence", "Sequence"
        ] if c in df.columns),
        None
    )

    lab_col = next(
        (c for c in [
            "Label", "label", "Y", "y",
            "interaction", "Interaction"
        ] if c in df.columns),
        None
    )

    if None in (drug_col, prot_col, lab_col):
        raise ValueError(f"Columns not found. Available: {list(df.columns)}")

    out = pd.DataFrame({
        "smiles": df[drug_col].astype(str).str.strip().str.replace(" ", "", regex=False),
        "target_seq": df[prot_col].astype(str).str.strip().str.replace(" ", "", regex=False).str.upper(),
        "label": pd.to_numeric(df[lab_col], errors="coerce"),
    }).dropna()

    out["label"] = out["label"].astype(int)

    return out.reset_index(drop=True)

def load_davis():
    p = DAVIS_BASE

    tr = standardize_df(_read_csv(os.path.join(p, "train.csv")))
    va = standardize_df(_read_csv(os.path.join(p, "val.csv")))
    te = standardize_df(_read_csv(os.path.join(p, "test.csv")))

    for split, df in [("train", tr), ("valid", va), ("test", te)]:
        counts = df["label"].value_counts().to_dict()
        print(f"  {split}: n={len(df)} label_counts={counts}")

    return tr, va, te



class DTIDataset(Dataset):
    def __init__(
        self,
        df,
        max_prot_len=1200,
        max_drug_len=128,
        k_window=3,
        use_esm_cache=True,
        use_drug_cache=True
    ):
        self.df = df.dropna(subset=["smiles", "target_seq", "label"]).reset_index(drop=True)
        self.max_prot_len = int(max_prot_len)
        self.max_drug_len = int(max_drug_len)
        self.k_window = int(k_window)
        self.use_esm_cache = use_esm_cache
        self.use_drug_cache = use_drug_cache

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        pf, pa, pm = esm2_embed_sequence(
            row["target_seq"],
            max_len=self.max_prot_len,
            k=self.k_window,
            use_cache=self.use_esm_cache
        )

        di, dm = tokenize_drug_smiles(
            row["smiles"],
            max_len=self.max_drug_len,
            use_cache=self.use_drug_cache
        )

        return {
            "prot_node_feats": pf,
            "prot_adj": pa,
            "prot_mask": pm,
            "drug_input_ids": di,
            "drug_attention_mask": dm,
            "label": torch.tensor(float(row["label"]), dtype=torch.float32),
        }




class ChemBERTEncoder(nn.Module):
    def __init__(self, output_dim=768, unfreeze_last_n=2):
        super().__init__()

        self.bert = AutoModel.from_pretrained("seyonec/ChemBERTa-zinc-base-v1")

        for p in self.bert.parameters():
            p.requires_grad = False

        if unfreeze_last_n > 0:
            for layer in self.bert.encoder.layer[-unfreeze_last_n:]:
                for p in layer.parameters():
                    p.requires_grad = True

        self.proj = nn.Sequential(
            nn.LayerNorm(self.bert.config.hidden_size),
            nn.Linear(self.bert.config.hidden_size, output_dim),
            nn.GELU(),
            nn.Dropout(0.1),
        )

    def forward(self, ids, mask):
        cls = self.bert(input_ids=ids, attention_mask=mask).last_hidden_state[:, 0, :]
        return self.proj(cls)


class GraphBERTNodeEncoder(nn.Module):
    def __init__(self, node_dim, hidden_dim=768, nhead=8, num_layers=3, unfreeze_last_n=2):
        super().__init__()

        self.node_embed = nn.Sequential(
            nn.Linear(node_dim, hidden_dim),
            nn.LayerNorm(hidden_dim)
        )

        enc_layer = nn.TransformerEncoderLayer(
            d_model=hidden_dim,
            nhead=nhead,
            batch_first=True,
            norm_first=True,
            dim_feedforward=hidden_dim * 4,
            dropout=0.1,
            activation="gelu"
        )

        self.encoder = nn.TransformerEncoder(enc_layer, num_layers=num_layers)

        for p in self.encoder.parameters():
            p.requires_grad = False

        if unfreeze_last_n > 0:
            for layer in self.encoder.layers[-unfreeze_last_n:]:
                for p in layer.parameters():
                    p.requires_grad = True

    def forward(self, nodes, mask, adj):
        x = self.node_embed(nodes)

        adj_f = adj.float()
        deg = adj_f.sum(dim=-1, keepdim=True).clamp(min=1.0)

        x = x + 0.1 * (torch.bmm(adj_f, x) / deg)
        x = self.encoder(x, src_key_padding_mask=(mask == 0))

        return x


def masked_mean(x, mask):
    m = mask.unsqueeze(-1)
    return (x * m).sum(1) / m.sum(1).clamp(min=1.0)


class BiCrossAttentionFusion(nn.Module):
    def __init__(self, d_model=768, num_heads=8, dropout=0.1):
        super().__init__()

        self.d2p = nn.MultiheadAttention(
            d_model,
            num_heads,
            dropout=dropout,
            batch_first=True
        )

        self.p2d = nn.MultiheadAttention(
            d_model,
            num_heads,
            dropout=dropout,
            batch_first=True
        )

        self.out = nn.Sequential(
            nn.Linear(d_model * 2, d_model),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(d_model, d_model)
        )

        self.norm = nn.LayerNorm(d_model)

    def forward(self, drug_vec, prot_nodes, prot_mask):
        q = drug_vec.unsqueeze(1)
        key_pad = (prot_mask == 0)

        dctx, _ = self.d2p(
            q,
            prot_nodes,
            prot_nodes,
            key_padding_mask=key_pad
        )

        dctx = dctx.squeeze(1)

        pctx, _ = self.p2d(
            prot_nodes,
            drug_vec.unsqueeze(1),
            drug_vec.unsqueeze(1)
        )

        fused = self.norm(
            self.out(torch.cat([dctx, masked_mean(pctx, prot_mask)], dim=-1)) + drug_vec
        )

        return fused, dctx, masked_mean(pctx, prot_mask)


class VAE(nn.Module):
    def __init__(self, input_dim=768, latent_dim=256):
        super().__init__()

        self.encoder = nn.Sequential(
            nn.Linear(input_dim, 512),
            nn.LayerNorm(512),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(512, 256),
            nn.LayerNorm(256),
            nn.ReLU(),
            nn.Dropout(0.2),
        )

        self.fc_mu = nn.Linear(256, latent_dim)
        self.fc_logvar = nn.Linear(256, latent_dim)

        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, 256),
            nn.LayerNorm(256),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(256, 512),
            nn.LayerNorm(512),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(512, input_dim)
        )

    def encode(self, x):
        h = self.encoder(x)
        return self.fc_mu(h), self.fc_logvar(h).clamp(-10, 10)

    def reparameterize(self, mu, logvar):
        return mu + torch.randn_like(mu) * torch.exp(0.5 * logvar)

    def forward(self, x):
        mu, logvar = self.encode(x)
        z = self.reparameterize(mu, logvar)
        recon = self.decoder(z)
        return recon, mu, logvar, z


class Discriminator(nn.Module):
    def __init__(self, input_dim=768, hidden_dim=512):
        super().__init__()

        SN = nn.utils.spectral_norm

        self.net = nn.Sequential(
            SN(nn.Linear(input_dim, hidden_dim)),
            nn.LeakyReLU(0.2, True),
            nn.Dropout(0.3),
            SN(nn.Linear(hidden_dim, hidden_dim // 2)),
            nn.LeakyReLU(0.2, True),
            nn.Dropout(0.3),
            SN(nn.Linear(hidden_dim // 2, 1))
        )

    def forward(self, x):
        return self.net(x)


class CosineClassifier(nn.Module):
    def __init__(self, input_dim=256, scale=10.0):
        super().__init__()

        self.weight = nn.Parameter(torch.randn(2, input_dim))
        nn.init.xavier_uniform_(self.weight.unsqueeze(0))

        self.scale = scale

        self.refine = nn.Sequential(
            nn.Linear(input_dim, input_dim),
            nn.LayerNorm(input_dim),
            nn.ReLU(),
            nn.Dropout(0.3)
        )

    def forward(self, z):
        z_r = self.refine(z)
        z_n = F.normalize(z_r, dim=-1)
        w_n = F.normalize(self.weight, dim=-1)

        logit = self.scale * torch.matmul(z_n, w_n.T)

        return logit[:, 1:2] - logit[:, 0:1]


class CrossAttnVAE(nn.Module):
    def __init__(self, d_model=768, latent_dim=256, drug_unfreeze=2, prot_unfreeze=2):
        super().__init__()

        self.latent_dim = latent_dim

        self.drug_encoder = ChemBERTEncoder(
            output_dim=d_model,
            unfreeze_last_n=drug_unfreeze
        )

        self.protein_node_encoder = GraphBERTNodeEncoder(
            node_dim=ESM_DIM,
            hidden_dim=d_model,
            unfreeze_last_n=prot_unfreeze
        )

        self.cross_fusion = BiCrossAttentionFusion(
            d_model=d_model,
            num_heads=8,
            dropout=0.1
        )

        self.vae = VAE(
            input_dim=d_model,
            latent_dim=latent_dim
        )

        self.classifier = CosineClassifier(
            input_dim=latent_dim,
            scale=10.0
        )

    def forward(self, drug_ids, drug_mask, prot_feats, prot_mask, prot_adj):
        drug_vec = self.drug_encoder(drug_ids, drug_mask)
        prot_nodes = self.protein_node_encoder(prot_feats, prot_mask, prot_adj)

        fused, dctx, pctx = self.cross_fusion(
            drug_vec,
            prot_nodes,
            prot_mask
        )

        recon, mu, logvar, z = self.vae(fused)
        pred_logit = self.classifier(z)

        return {
            "prediction": pred_logit,
            "reconstruction": recon,
            "mu": mu,
            "logvar": logvar,
            "z": z,
            "fused": fused,
            "drug_ctx": dctx,
            "prot_ctx": pctx,
        }




def kl_div(mu, logvar):
    return 0.5 * torch.mean(torch.exp(logvar) + mu ** 2 - 1.0 - logvar)


class AsymmetricFocalLoss(nn.Module):
    def __init__(
        self,
        pos_weight=None,
        gamma_pos=0.0,
        gamma_neg=4.0,
        label_smoothing=0.01,
        clip=0.05
    ):
        super().__init__()

        self.gamma_pos = gamma_pos
        self.gamma_neg = gamma_neg
        self.ls = label_smoothing
        self.clip = clip
        self.pos_weight = pos_weight

    def forward(self, logit, target):
        target_s = target * (1 - self.ls) + 0.5 * self.ls

        bce = F.binary_cross_entropy_with_logits(
            logit,
            target_s,
            pos_weight=self.pos_weight,
            reduction="none"
        )

        prob = torch.sigmoid(logit)
        prob_neg = (prob + self.clip).clamp(max=1.0)

        pos_w = (1 - prob) ** self.gamma_pos
        neg_w = prob_neg ** self.gamma_neg

        fw = target * pos_w + (1 - target) * neg_w

        return (fw * bce).mean()


def prototypical_contrastive_loss(z, labels, temp=0.07):
    z_norm = F.normalize(z, dim=-1)
    unique_labels = labels.unique()

    if len(unique_labels) < 2:
        return torch.tensor(0.0, device=z.device)

    prototypes = torch.stack([
        z_norm[labels == lbl].mean(0)
        for lbl in unique_labels
    ])

    prototypes = F.normalize(prototypes, dim=-1)

    sim = torch.matmul(z_norm, prototypes.T) / temp

    label_idx = torch.stack([
        (labels == lbl).float()
        for lbl in unique_labels
    ], dim=1)

    target = label_idx / label_idx.sum(1, keepdim=True).clamp(min=1)

    return F.cross_entropy(sim, target.argmax(1))


def latent_mixup(fused, labels, alpha=0.4, p_mixup=0.5):
    if random.random() > p_mixup:
        return fused, labels

    lam = np.random.beta(alpha, alpha)
    idx = torch.randperm(fused.size(0), device=fused.device)

    return (
        lam * fused + (1 - lam) * fused[idx],
        lam * labels + (1 - lam) * labels[idx]
    )


_adv_bce = nn.BCEWithLogitsLoss()

def r1_gradient_penalty(disc, real, gamma=1.0):
    real_in = real.detach().requires_grad_(True)
    real_logit = disc(real_in)

    grads = torch.autograd.grad(
        outputs=real_logit.sum(),
        inputs=real_in,
        create_graph=True,
        retain_graph=True
    )[0]

    return gamma * 0.5 * grads.pow(2).sum(dim=1).mean()


def discriminator_loss(disc, real, fake, gamma_r1=1.0):
    real_logit = disc(real.detach())
    fake_logit = disc(fake.detach())

    d_loss = 0.5 * (
        _adv_bce(real_logit, torch.ones_like(real_logit)) +
        _adv_bce(fake_logit, torch.zeros_like(fake_logit))
    )

    return d_loss + r1_gradient_penalty(disc, real, gamma=gamma_r1)


def generator_adversarial_loss(disc, fake):
    return _adv_bce(disc(fake), torch.ones_like(disc(fake)))




def sigmoid_np(x):
    return 1.0 / (1.0 + np.exp(-np.clip(x, -88, 88)))


def compute_metrics(y_true, y_logit, th=0.5):
    y_true = np.asarray(y_true).astype(int)
    y_prob = sigmoid_np(np.asarray(y_logit).astype(float))
    y_pred = (y_prob >= th).astype(int)

    out = {}

    try:
        out["AUROC"] = float(roc_auc_score(y_true, y_prob))
    except Exception:
        out["AUROC"] = float("nan")

    try:
        out["AUPRC"] = float(average_precision_score(y_true, y_prob))
    except Exception:
        out["AUPRC"] = float("nan")

    out["F1"] = float(f1_score(y_true, y_pred, zero_division=0))
    out["ACC"] = float(accuracy_score(y_true, y_pred))
    out["PREC"] = float(precision_score(y_true, y_pred, zero_division=0))
    out["REC"] = float(recall_score(y_true, y_pred, zero_division=0))

    out["MCC"] = (
        float(matthews_corrcoef(y_true, y_pred))
        if len(np.unique(y_true)) > 1
        else 0.0
    )

    tn, fp, fn, tp = confusion_matrix(
        y_true,
        y_pred,
        labels=[0, 1]
    ).ravel()

    out["SENS"] = float(tp / (tp + fn)) if (tp + fn) > 0 else 0.0
    out["SPEC"] = float(tn / (tn + fp)) if (tn + fp) > 0 else 0.0
    out["TH"] = float(th)

    return out


@torch.no_grad()
def evaluate_logits(model, loader):
    model.eval()

    y_true, y_logit = [], []

    for batch in loader:
        out = model(
            batch["drug_input_ids"].to(device),
            batch["drug_attention_mask"].to(device),
            batch["prot_node_feats"].to(device),
            batch["prot_mask"].to(device),
            batch["prot_adj"].to(device)
        )

        y_true.extend(batch["label"].cpu().numpy().tolist())
        y_logit.extend(
            out["prediction"].squeeze(-1).detach().cpu().numpy().tolist()
        )

    return np.array(y_true), np.array(y_logit)


def evaluate_best_th(model, loader):
    y_true, y_logit = evaluate_logits(model, loader)
    y_prob = sigmoid_np(y_logit)

    prec, rec, thresholds = precision_recall_curve(y_true, y_prob)

    f1_scores = 2 * prec[:-1] * rec[:-1] / (
        prec[:-1] + rec[:-1] + 1e-8
    )

    best_th = float(thresholds[int(np.argmax(f1_scores))])

    return compute_metrics(y_true, y_logit, th=best_th)


def platt_calibrate(val_logits, val_labels, test_logits):
    cal = LogisticRegression(
        C=1.0,
        max_iter=2000,
        solver="lbfgs"
    )

    cal.fit(val_logits.reshape(-1, 1), val_labels.astype(int))

    test_probs = cal.predict_proba(test_logits.reshape(-1, 1))[:, 1]

    eps = 1e-7
    test_probs = np.clip(test_probs, eps, 1 - eps)

    return np.log(test_probs / (1 - test_probs))


@torch.no_grad()
def ensemble_logits(model_a, model_b, loader, weight_a=0.6):
    model_a.eval()
    model_b.eval()

    y_true, logits_a, logits_b = [], [], []

    for batch in loader:

        def _fwd(m):
            return m(
                batch["drug_input_ids"].to(device),
                batch["drug_attention_mask"].to(device),
                batch["prot_node_feats"].to(device),
                batch["prot_mask"].to(device),
                batch["prot_adj"].to(device)
            )

        la = _fwd(model_a)["prediction"].squeeze(-1).cpu().numpy()
        lb = _fwd(model_b)["prediction"].squeeze(-1).cpu().numpy()

        y_true.extend(batch["label"].cpu().numpy())
        logits_a.extend(la)
        logits_b.extend(lb)

    ensemble = weight_a * np.array(logits_a) + (1 - weight_a) * np.array(logits_b)

    return np.array(y_true), ensemble




def train_one_epoch(
    model,
    disc,
    loader,
    opt_main,
    opt_disc,
    loss_fn,
    w_kl=0.02,
    w_rec=0.3,
    w_con=0.2,
    w_adv=0.5,
    grad_accum_steps=4,
    mixup_alpha=0.4,
    p_mixup=0.5
):
    model.train()
    disc.train()

    total_loss = 0.0

    opt_main.zero_grad(set_to_none=True)
    opt_disc.zero_grad(set_to_none=True)

    for step_idx, batch in enumerate(tqdm(loader, desc="Train", leave=False)):
        drug_ids = batch["drug_input_ids"].to(device)
        drug_mask = batch["drug_attention_mask"].to(device)
        prot_feats = batch["prot_node_feats"].to(device)
        prot_mask = batch["prot_mask"].to(device)
        prot_adj = batch["prot_adj"].to(device)
        labels = batch["label"].to(device)

        out = model(
            drug_ids,
            drug_mask,
            prot_feats,
            prot_mask,
            prot_adj
        )

        pred_logit = out["prediction"].squeeze(-1)
        fused = out["fused"]
        mu, logvar = out["mu"], out["logvar"]

        fused_m, labels_m = latent_mixup(
            fused,
            labels,
            alpha=mixup_alpha,
            p_mixup=p_mixup
        )

        recon_m, mu_m, logvar_m, z_m = model.vae(fused_m)

        d_loss = discriminator_loss(disc, fused, recon_m) / grad_accum_steps
        d_loss.backward(retain_graph=True)

        if (step_idx + 1) % grad_accum_steps == 0:
            torch.nn.utils.clip_grad_norm_(disc.parameters(), 1.0)
            opt_disc.step()
            opt_disc.zero_grad(set_to_none=True)

        cls_loss = loss_fn(pred_logit, labels)
        kl_loss = kl_div(mu_m, logvar_m)
        adv_g = generator_adversarial_loss(disc, recon_m)
        mse_a = F.mse_loss(recon_m, fused_m.detach())
        con_loss = prototypical_contrastive_loss(
            z_m,
            labels_m.round().long()
        )

        rec_loss = w_adv * adv_g + (1.0 - w_adv) * mse_a

        loss = (
            cls_loss +
            w_rec * rec_loss +
            w_kl * kl_loss +
            w_con * con_loss
        )

        (loss / grad_accum_steps).backward()

        if (step_idx + 1) % grad_accum_steps == 0:
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            opt_main.step()
            opt_main.zero_grad(set_to_none=True)

        total_loss += float(loss.detach().cpu())

    return total_loss / max(1, len(loader))




def get_loaders(
    batch_size=8,
    max_prot_len=1200,
    max_drug_len=128,
    k_window=3,
    use_esm_cache=True,
    use_drug_cache=True
):
    tr_df, va_df, te_df = load_davis()

    kw = dict(
        max_prot_len=max_prot_len,
        max_drug_len=max_drug_len,
        k_window=k_window,
        use_esm_cache=use_esm_cache,
        use_drug_cache=use_drug_cache
    )

    train_ds = DTIDataset(tr_df, **kw)
    valid_ds = DTIDataset(va_df, **kw)
    test_ds = DTIDataset(te_df, **kw)

    nw = 0
    pm = bool(torch.cuda.is_available())

    train_loader = DataLoader(
        train_ds,
        batch_size=batch_size,
        shuffle=True,
        num_workers=nw,
        pin_memory=pm,
        drop_last=True
    )

    valid_loader = DataLoader(
        valid_ds,
        batch_size=batch_size,
        shuffle=False,
        num_workers=nw,
        pin_memory=pm
    )

    test_loader = DataLoader(
        test_ds,
        batch_size=batch_size,
        shuffle=False,
        num_workers=nw,
        pin_memory=pm
    )

    return train_loader, valid_loader, test_loader




def save_checkpoint(
    path,
    epoch,
    model,
    disc,
    opt_main,
    opt_disc,
    swa_model,
    best_auroc,
    history,
    th,
    swa_active
):
    payload = {
        "epoch": epoch,
        "model": model.state_dict(),
        "disc": disc.state_dict(),
        "opt_main": opt_main.state_dict(),
        "opt_disc": opt_disc.state_dict(),
        "swa_model": swa_model.state_dict(),
        "best_auroc": best_auroc,
        "history": history,
        "th": th,
        "swa_active": swa_active,
    }

    torch.save(payload, path)
    mirror_to_drive(path)


def load_checkpoint(path, model, disc, opt_main, opt_disc, swa_model):
    if not os.path.exists(path) and DRIVE_AVAILABLE:
        drive_src = drive_path(path)

        if os.path.exists(drive_src):
            print(f"  📥 Restoring checkpoint from Drive: {drive_src}")
            shutil.copy2(drive_src, path)

    if not os.path.exists(path):
        return None

    ckpt = torch.load(path, map_location=device)

    model.load_state_dict(ckpt["model"])
    disc.load_state_dict(ckpt["disc"])
    opt_main.load_state_dict(ckpt["opt_main"])
    opt_disc.load_state_dict(ckpt["opt_disc"])
    swa_model.load_state_dict(ckpt["swa_model"])

    print(
        f"  ✅ Resumed from epoch {ckpt['epoch']} "
        f"(best AUROC so far: {ckpt['best_auroc']:.4f})"
    )

    return ckpt


def save_best_model(path, model, disc, th):
    torch.save(
        {
            "model": model.state_dict(),
            "disc": disc.state_dict(),
            "th": th
        },
        path
    )

    mirror_to_drive(path)




def run_davis_evaluation(seed: int) -> dict:
    NUM_EPOCHS = 120
    PATIENCE = 25

    LR = 3e-5
    LR_DISC = 1e-4
    WEIGHT_DECAY = 1e-3

    W_KL = 0.02
    W_REC = 0.3
    W_CON = 0.2
    W_ADV = 0.5

    GRAD_ACCUM = 4

    SWA_START = 45
    SWA_LR = 5e-6
    WARMUP_EPOCHS = 15

    ckpt_path = os.path.join(SAVE_DIR, f"checkpoint_seed{seed}.pth")
    best_path = os.path.join(SAVE_DIR, f"best_model_DAVIS_v4_seed{seed}.pth")
    history_path = os.path.join(SAVE_DIR, f"history_v4_seed{seed}.json")
    results_path = os.path.join(SAVE_DIR, f"DAVIS_results_v4_seed{seed}.csv")
    plot_path = os.path.join(SAVE_DIR, f"training_curves_v4_seed{seed}.png")

    print("\n" + "=" * 70)
    print(f"DAVIS DTI — VAE-GAN v4 (seed={seed})")
    print(f"Checkpoint : {ckpt_path}")
    print(f"Drive dir  : {DRIVE_SAVE_DIR if DRIVE_AVAILABLE else 'N/A'}")
    print("=" * 70)

    train_loader, valid_loader, test_loader = get_loaders(batch_size=8)

    model = CrossAttnVAE(
        d_model=768,
        latent_dim=256,
        drug_unfreeze=2,
        prot_unfreeze=2
    ).to(device)

    disc = Discriminator(
        input_dim=768,
        hidden_dim=512
    ).to(device)

    loss_fn = AsymmetricFocalLoss(
        pos_weight=None,
        gamma_pos=0.0,
        gamma_neg=4.0,
        label_smoothing=0.01,
        clip=0.05
    )

    pretrained_ids = (
        set(id(p) for p in model.drug_encoder.bert.parameters()) |
        set(id(p) for p in model.protein_node_encoder.encoder.parameters())
    )

    main_pretrained = [
        p for p in model.parameters()
        if p.requires_grad and id(p) in pretrained_ids
    ]

    main_new = [
        p for p in model.parameters()
        if p.requires_grad and id(p) not in pretrained_ids
    ]

    opt_main = torch.optim.AdamW(
        [
            {"params": main_pretrained, "lr": LR * 0.1},
            {"params": main_new, "lr": LR},
        ],
        weight_decay=WEIGHT_DECAY
    )

    opt_disc = torch.optim.AdamW(
        disc.parameters(),
        lr=LR_DISC,
        betas=(0.5, 0.999),
        weight_decay=1e-4
    )

    swa_model = AveragedModel(model)
    swa_sched = SWALR(
        opt_main,
        swa_lr=SWA_LR,
        anneal_epochs=5
    )

    swa_active = False

    warmup_sched = torch.optim.lr_scheduler.LambdaLR(
        opt_main,
        lr_lambda=lambda ep: min(1.0, (ep + 1) / WARMUP_EPOCHS)
    )

    cosine_sched = torch.optim.lr_scheduler.CosineAnnealingWarmRestarts(
        opt_main,
        T_0=20,
        T_mult=1,
        eta_min=1e-7
    )

    def step_scheduler(epoch):
        if epoch >= SWA_START:
            return

        if epoch < WARMUP_EPOCHS:
            warmup_sched.step()
        else:
            cosine_sched.step(epoch - WARMUP_EPOCHS)

    best_auroc = -1.0
    wait = 0
    start_epoch = 1

    history = {
        "loss": [],
        "val_auroc": [],
        "val_auprc": []
    }

    ckpt = load_checkpoint(
        ckpt_path,
        model,
        disc,
        opt_main,
        opt_disc,
        swa_model
    )

    if ckpt is not None:
        start_epoch = ckpt["epoch"] + 1
        best_auroc = ckpt["best_auroc"]
        history = ckpt["history"]
        swa_active = ckpt["swa_active"]
        print(f"  ▶ Continuing from epoch {start_epoch}")
    else:
        print("  ▶ Starting fresh (no checkpoint found)")

    for ep in range(start_epoch, NUM_EPOCHS + 1):
        tr_loss = train_one_epoch(
            model,
            disc,
            train_loader,
            opt_main,
            opt_disc,
            loss_fn,
            w_kl=W_KL,
            w_rec=W_REC,
            w_con=W_CON,
            w_adv=W_ADV,
            grad_accum_steps=GRAD_ACCUM,
            mixup_alpha=0.4,
            p_mixup=0.5
        )

        if ep >= SWA_START:
            swa_model.update_parameters(model)
            swa_sched.step()
            swa_active = True

        valid_m = evaluate_best_th(model, valid_loader)

        history["loss"].append(tr_loss)
        history["val_auroc"].append(valid_m["AUROC"])
        history["val_auprc"].append(valid_m["AUPRC"])

        swa_tag = " [SWA]" if swa_active else ""

        print(
            f"Epoch {ep:03d} | "
            f"Loss {tr_loss:.4f} | "
            f"AUROC {valid_m['AUROC']:.4f} "
            f"AUPRC {valid_m['AUPRC']:.4f} "
            f"F1 {valid_m['F1']:.4f} "
            f"SENS {valid_m['SENS']:.4f} "
            f"SPEC {valid_m['SPEC']:.4f} "
            f"TH {valid_m['TH']:.3f}{swa_tag}"
        )

        if valid_m["AUROC"] > best_auroc:
            best_auroc = valid_m["AUROC"]
            save_best_model(best_path, model, disc, valid_m["TH"])
            wait = 0
            print(f"  ✓ New best AUROC {best_auroc:.4f} — saved ✅")
        else:
            wait += 1

            if wait >= PATIENCE:
                print(f"  Early stopping at epoch {ep} (patience={PATIENCE})")

                save_checkpoint(
                    ckpt_path,
                    ep,
                    model,
                    disc,
                    opt_main,
                    opt_disc,
                    swa_model,
                    best_auroc,
                    history,
                    valid_m["TH"],
                    swa_active
                )

                break

        save_checkpoint(
            ckpt_path,
            ep,
            model,
            disc,
            opt_main,
            opt_disc,
            swa_model,
            best_auroc,
            history,
            valid_m["TH"],
            swa_active
        )

        step_scheduler(ep - 1)

    if swa_active:
        print("\nUpdating SWA batch-norm statistics...")
        update_bn(train_loader, swa_model, device=device)

    print("\nLoading best checkpoint for evaluation...")

    if not os.path.exists(best_path) and DRIVE_AVAILABLE:
        drive_src = drive_path(best_path)

        if os.path.exists(drive_src):
            shutil.copy2(drive_src, best_path)

    ckpt_best = torch.load(best_path, map_location=device)

    best_model = CrossAttnVAE(
        d_model=768,
        latent_dim=256,
        drug_unfreeze=2,
        prot_unfreeze=2
    ).to(device)

    best_model.load_state_dict(ckpt_best["model"])

    print("Fitting Platt calibration on validation set...")

    val_true, val_logit = evaluate_logits(best_model, valid_loader)
    test_true, test_logit = evaluate_logits(best_model, test_loader)

    test_logit_cal = platt_calibrate(
        val_logit,
        val_true,
        test_logit
    )

    val_logit_cal = platt_calibrate(
        val_logit,
        val_true,
        val_logit
    )

    y_prob_val = sigmoid_np(val_logit_cal)

    prec_v, rec_v, th_v = precision_recall_curve(
        val_true,
        y_prob_val
    )

    f1_v = 2 * prec_v[:-1] * rec_v[:-1] / (
        prec_v[:-1] + rec_v[:-1] + 1e-8
    )

    th_cal = float(th_v[int(np.argmax(f1_v))])

    test_m_cal = compute_metrics(
        test_true,
        test_logit_cal,
        th=th_cal
    )

    print(
        f"\n[Best ckpt, calibrated] "
        f"AUROC {test_m_cal['AUROC']:.4f} "
        f"AUPRC {test_m_cal['AUPRC']:.4f} "
        f"F1 {test_m_cal['F1']:.4f} "
        f"SENS {test_m_cal['SENS']:.4f} "
        f"SPEC {test_m_cal['SPEC']:.4f} "
        f"TH {test_m_cal['TH']:.3f}"
    )

    if swa_active:
        print("\nBuilding SWA + best-ckpt ensemble...")

        ens_true, ens_logit = ensemble_logits(
            swa_model.module,
            best_model,
            test_loader,
            weight_a=0.6
        )

        _, val_logit_swa = evaluate_logits(
            swa_model.module,
            valid_loader
        )

        val_ens_logit = 0.6 * val_logit_swa + 0.4 * val_logit

        ens_logit_cal = platt_calibrate(
            val_ens_logit,
            val_true,
            ens_logit
        )

        y_prob_ens = sigmoid_np(ens_logit_cal)

        prec_e, rec_e, th_e = precision_recall_curve(
            ens_true,
            y_prob_ens
        )

        f1_e = 2 * prec_e[:-1] * rec_e[:-1] / (
            prec_e[:-1] + rec_e[:-1] + 1e-8
        )

        th_ens = float(th_e[int(np.argmax(f1_e))])

        final_m = compute_metrics(
            ens_true,
            ens_logit_cal,
            th=th_ens
        )

        label_used = "SWA + best-ckpt ensemble (Platt calibrated)"
    else:
        final_m = test_m_cal
        label_used = "best-ckpt (Platt calibrated)"

    show = ["AUROC", "AUPRC", "F1", "ACC", "MCC", "SENS", "SPEC", "TH"]
    report_df = pd.DataFrame({"davis": final_m}).T

    print(f"\n{'=' * 70}")
    print(f"SEED {seed} TEST RESULT [{label_used}]")
    print(report_df[show].to_string())
    print(f"{'=' * 70}")

    report_df.to_csv(results_path)
    mirror_to_drive(results_path)

    print(f"Results saved → local: {results_path}")

    if DRIVE_AVAILABLE:
        print(f"             → Drive: {drive_path(results_path)}")

    with open(history_path, "w") as f:
        json.dump(history, f)

    mirror_to_drive(history_path)

    epochs = list(range(1, len(history["loss"]) + 1))

    fig, axes = plt.subplots(1, 3, figsize=(15, 4))
    fig.suptitle(f"DAVIS DTI v4 — seed={seed}", fontsize=13)

    axes[0].plot(epochs, history["loss"])
    axes[0].axvline(SWA_START, linestyle="--", linewidth=1, label="SWA start")
    axes[0].set_title("Training loss")
    axes[0].set_xlabel("Epoch")
    axes[0].legend()

    axes[1].plot(epochs, history["val_auroc"])
    axes[1].axvline(SWA_START, linestyle="--", linewidth=1, label="SWA start")
    axes[1].set_title("Val AUROC")
    axes[1].set_xlabel("Epoch")
    axes[1].legend()

    axes[2].plot(epochs, history["val_auprc"])
    axes[2].axvline(SWA_START, linestyle="--", linewidth=1, label="SWA start")
    axes[2].set_title("Val AUPRC")
    axes[2].set_xlabel("Epoch")
    axes[2].legend()

    plt.tight_layout()
    plt.savefig(plot_path, dpi=150)
    plt.close()

    mirror_to_drive(plot_path)

    print(f"Curves saved → local: {plot_path}")

    if DRIVE_AVAILABLE:
        print(f"             → Drive: {drive_path(plot_path)}")

    return final_m




for SEED in SEEDS:
    print(f"\n{'#' * 70}")
    print(f"# SEED {SEED} ({SEEDS.index(SEED) + 1}/{len(SEEDS)})")
    print(f"{'#' * 70}")

    seed_everything(SEED)

    result = run_davis_evaluation(seed=SEED)
    result["seed"] = SEED

    all_results.append(result)



METRICS = [
    "AUROC",
    "AUPRC",
    "F1",
    "ACC",
    "MCC",
    "SENS",
    "SPEC"
]

results_df = pd.DataFrame(all_results)
results_df.set_index("seed", inplace=True)

summary = pd.DataFrame({
    "mean": results_df[METRICS].mean(),
    "var": results_df[METRICS].var(),
    "std": results_df[METRICS].std(),
})

print(f"\n{'=' * 70}")
print(f"MULTI-SEED SUMMARY (seeds: {SEEDS})")
print(f"{'=' * 70}")
print(summary.to_string(float_format=lambda x: f"{x:.6f}"))
print(f"{'=' * 70}")

print("\nMean ± Std:")

for metric in METRICS:
    print(
        f"  {metric:6s}: "
        f"{summary.loc[metric, 'mean']:.4f} ± "
        f"{summary.loc[metric, 'std']:.4f}"
    )

all_seeds_path = os.path.join(SAVE_DIR, "DAVIS_all_seeds_v4.csv")
summary_path = os.path.join(SAVE_DIR, "DAVIS_multi_seed_summary_v4.csv")

results_df.to_csv(all_seeds_path)
summary.to_csv(summary_path)

mirror_to_drive(all_seeds_path)
mirror_to_drive(summary_path)

print(f"\nPer-seed results   → {all_seeds_path}")
print(f"Summary mean/std   → {summary_path}")

if DRIVE_AVAILABLE:
    print(f"Drive mirror       → {DRIVE_SAVE_DIR}")




fig, ax = plt.subplots(figsize=(10, 5))

x = np.arange(len(METRICS))
means = summary.loc[METRICS, "mean"].values
stds = summary.loc[METRICS, "std"].values

bars = ax.bar(
    x,
    means,
    yerr=stds,
    capsize=5
)

ax.set_xticks(x)
ax.set_xticklabels(METRICS, fontsize=12)
ax.set_ylim(0, 1.05)
ax.set_ylabel("Score", fontsize=12)
ax.set_title(
    f"DAVIS DTI v4 — Mean ± Std (seeds: {SEEDS})",
    fontsize=13
)

ax.yaxis.grid(True, linestyle="--", alpha=0.6)
ax.set_axisbelow(True)

for bar, m, s in zip(bars, means, stds):
    ax.text(
        bar.get_x() + bar.get_width() / 2,
        m + s + 0.01,
        f"{m:.3f}",
        ha="center",
        va="bottom",
        fontsize=9
    )

plt.tight_layout()

summary_plot = os.path.join(SAVE_DIR, "multi_seed_summary_v4.png")
plt.savefig(summary_plot, dpi=150)
plt.show()

mirror_to_drive(summary_plot)

print(f"Summary chart saved → {summary_plot}")
print("\n✅ Done.")